language: php
php:
- 7.0
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
install:
- composer install
script: vendor/bin/phpunit  --coverage-clover build/logs/clover.xml
after_success:
- if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then travis_retry php vendor/bin/coveralls
  -v; fi
